// <auto-generated />
using System;
using EventListenerService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventListenerService.Migrations
{
    [DbContext(typeof(WojtusContext))]
    [Migration("20250517171734_AddMemeMetadata")]
    partial class AddMemeMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventListenerService.Models.MemeMessage", b =>
                {
                    b.Property<decimal>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("message_id");

                    b.Property<decimal>("AuthorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("author_id");

                    b.Property<string>("AuthorUsername")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_username");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("ImageUrlProxy")
                        .HasColumnType("text")
                        .HasColumnName("image_url_proxy");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("MessageId")
                        .HasName("pk_meme_messages");

                    b.ToTable("meme_messages", (string)null);
                });

            modelBuilder.Entity("EventListenerService.Models.MemeMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.PrimitiveCollection<string[]>("Keywords")
                        .HasColumnType("text[]")
                        .HasColumnName("keywords");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("message_id");

                    b.PrimitiveCollection<string[]>("Objects")
                        .HasColumnType("text[]")
                        .HasColumnName("objects");

                    b.Property<string>("TextContent")
                        .HasColumnType("text")
                        .HasColumnName("text_content");

                    b.Property<string>("Tone")
                        .HasColumnType("text")
                        .HasColumnName("tone");

                    b.HasKey("Id")
                        .HasName("pk_meme_metadata");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_meme_metadata_message_id");

                    b.ToTable("meme_metadata", (string)null);
                });

            modelBuilder.Entity("EventListenerService.Models.UserEmoji", b =>
                {
                    b.Property<decimal>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emoji");

                    b.HasKey("ID")
                        .HasName("pk_user_emojis");

                    b.ToTable("user_emojis", (string)null);
                });

            modelBuilder.Entity("EventListenerService.Models.MemeMetadata", b =>
                {
                    b.HasOne("EventListenerService.Models.MemeMessage", "MemeMessage")
                        .WithOne("Metadata")
                        .HasForeignKey("EventListenerService.Models.MemeMetadata", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meme_metadata_meme_messages_message_id");

                    b.Navigation("MemeMessage");
                });

            modelBuilder.Entity("EventListenerService.Models.MemeMessage", b =>
                {
                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
