"""The Prometheus alert rules of WojtusDiscord: prometheus/wojtusdiscord-alerts.yml.

This file is the source of truth for the rule file. build.py calls write(); run build.py,
not this module. HEAD is the static part (Postgres and Tempo rules); the bot rules follow
as rule(...) calls. Every rule is severity warning, service wojtusdiscord.

To add an alert: add a rule(...) call below, add a case to ../prometheus/tests/alerts_test.yml,
run build.py, then `../sync.sh --check`.
"""
import os

from lib import ERRORS, FAILED, J, NOT_OK, xinc

MS = "wojtus_meme_search_duration_seconds"
API = 'http_route=~"/?api/.*"'
# A 503 of the meme dashboard is an answer the bot chose (a cap or a wait that ran out):
# WojtusMemeDashboardUnavailable judges those, WojtusApiServerErrors leaves them out.
ERR_5XX = 'http_response_status_code=~"5..",http_response_status_code!="503"'
HSC = "http_server_request_duration_seconds_count"

PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "prometheus", "wojtusdiscord-alerts.yml")

HEAD = r'''
# WojtusDiscord alert rules. GENERATED: do not edit this file.
# Source of truth: deploy/observability/tools/alerts.py in the WojtusDiscord repo.
# Change it there, run `python3 deploy/observability/tools/build.py`, then `./sync.sh`.
#
# Every rule starts as severity: warning (Alertmanager -> homelab-bot DM, 4h repeat).
# Promote to critical only after a baseline exists.
# Target-down is NOT repeated here: the host-wide InstanceDown / PrometheusTargetMissing
# rules already cover every job, including the ones below.
groups:
  - name: wojtusdiscord_postgres
    rules:
      # The exporter answers but cannot reach the database.
      - alert: WojtusPostgresDown
        expr: pg_up{job="wojtus-postgres"} == 0
        for: 2m
        labels:
          severity: warning
          service: wojtusdiscord
        annotations:
          summary: "wojtus-postgres does not accept connections"
          description: "postgres-exporter is up but pg_up is 0 for 2 minutes. The bot cannot write events."

      - alert: WojtusPostgresConnectionsHigh
        expr: |
          sum(pg_stat_activity_count{job="wojtus-postgres"})
            / max(pg_settings_max_connections{job="wojtus-postgres"}) > 0.8
        for: 10m
        labels:
          severity: warning
          service: wojtusdiscord
        annotations:
          summary: "wojtus-postgres uses {{ $value | humanizePercentage }} of max_connections"
          description: "Normal load is 3-10 connections of 100. Look for a connection leak or a stuck backfill."

      # A transaction open this long blocks vacuum and can hold locks against ingest.
      - alert: WojtusPostgresLongTransaction
        expr: pg_long_running_transactions_oldest_timestamp_seconds{job="wojtus-postgres"} > 1800
        for: 5m
        labels:
          severity: warning
          service: wojtusdiscord
        annotations:
          summary: "A transaction on wojtus-postgres is open for {{ $value | humanizeDuration }}"
          description: "Check pg_stat_activity for the oldest xact_start."

      - alert: WojtusPostgresDeadlocks
        expr: increase(pg_stat_database_deadlocks{job="wojtus-postgres",datname="discord_event_service"}[15m]) > 0
        labels:
          severity: warning
          service: wojtusdiscord
        annotations:
          summary: "{{ $value | printf \"%.0f\" }} deadlock(s) on discord_event_service in 15 minutes"
          description: "The upsert paths are written to avoid lock-order inversions; a deadlock is new behaviour."

      # Dead tuples above 20% of a table that is big enough to matter: autovacuum is not keeping up.
      - alert: WojtusPostgresDeadTuples
        expr: |
          pg_stat_user_tables_n_dead_tup{job="wojtus-postgres",datname="discord_event_service"}
            / (pg_stat_user_tables_n_live_tup + pg_stat_user_tables_n_dead_tup) > 0.2
          and pg_stat_user_tables_n_dead_tup > 50000
        for: 6h
        labels:
          severity: warning
          service: wojtusdiscord
        annotations:
          summary: "Table {{ $labels.relname }} is {{ $value | humanizePercentage }} dead tuples"
          description: "Autovacuum has not cleaned {{ $labels.schemaname }}.{{ $labels.relname }} for 6 hours."

      # Growth rate now: the slope of the database size over the last 6 hours, as bytes per day.
      # Fires when that slope stays above 500 MiB per day for 6 hours. It is not a forecast.
      - alert: WojtusPostgresRapidGrowth
        expr: |
          deriv(pg_database_size_bytes{job="wojtus-postgres",datname="discord_event_service"}[6h]) * 86400
            > 500 * 1024 * 1024
        for: 6h
        labels:
          severity: warning
          service: wojtusdiscord
        annotations:
          summary: "discord_event_service grows {{ $value | humanize1024 }}B per day"
          description: "Normal growth is a few MiB per day. Look for a runaway backfill or a raw-event flood."

  - name: wojtusdiscord_tempo
    rules:
      - alert: TempoIngestFailures
        expr: sum(rate(tempo_receiver_refused_spans{job="tempo"}[10m])) > 0
        for: 15m
        labels:
          severity: warning
          service: wojtusdiscord
        annotations:
          summary: "Tempo refuses spans"
          description: "Traces from discord-event-service are dropped at the receiver. Check docker logs tempo."
'''.lstrip("\n")


def xi(metric, extra, rng, step="1m"):
    return xinc(metric, ",".join(x for x in (J, extra) if x), rng, step)


def rule(name, expr, for_, summary, description, comment=None):
    out = "".join(f"      # {l}\n" for l in comment.split("\n")) if comment else ""
    out += f"      - alert: {name}\n        expr: |\n"
    out += "".join(f"          {l}\n" for l in expr.strip().split("\n"))
    if for_:
        out += f"        for: {for_}\n"
    out += "        labels:\n          severity: warning\n          service: wojtusdiscord\n        annotations:\n"
    out += f'          summary: "{summary}"\n          description: "{description}"\n\n'
    return out


b = """
  # Bot rules. The bot restarts on every deploy (a few times a day): its counters start again at
  # zero and the gateway is away for about 6 s. No rule here fires because of one restart.
  #
  # Counting. The bot creates a counter series on its first increment, and increase() never
  # counts the sample that creates a series. A rule on a rare event (a dead letter, a failed
  # run) would then miss the first event after every restart. Such rules use this form
  # (m = the counter, S = wojtus_process_start_time_seconds, U = wojtus_process_uptime_seconds):
  #   sum_over_time(((m - (PREV) >= 0) or (m + 0))[<window>:1m])
  #   PREV = ((last_over_time(m[10m] offset 1m) and on (job, instance) (U > 660))
  #            or (m offset 1m and on (job, instance) (U <= 660)))
  #          and on (job, instance) (S == last_over_time(S[10m] offset 1m))
  # Per minute it adds the value minus the earlier value of the same process life, and the full
  # value when there is no such earlier value (new series, or a restart since the last minute).
  # last_over_time keeps one failed scrape from counting a value twice. In the first 11 minutes
  # of a process life its window can hold a sample of the old process, so there the plain
  # instant value is used: it ends at the restart.
  # Limits: an increment in the last seconds before a restart is lost when no scrape saw it.
  # A Prometheus gap above 10 minutes, or a scrape without S and U, counts each full value once.
  # Tests: prometheus/tests/ (restart, new series, failed scrape), run by ./sync.sh --check.
  #
  # Quiet nights: no rule fires on missing events. There is no rule on the age of the last event
  # or on voice members: a 12-member server is silent for hours at night. The bot's HealthCheckJob
  # judges silence per event type; WojtusHealthCheckFailing carries its verdict.
  - name: wojtusdiscord_bot
    rules:
"""
b += rule("WojtusGatewayDisconnected",
          f"min by (job, instance)(wojtus_gateway_connected{{{J}}}) == 0", "5m",
          "The bot is not connected to the Discord gateway",
          "The process runs and answers scrapes, but wojtus_gateway_connected is 0 for 5 minutes. No event is ingested. Check the bot log for socket close codes and Discord status.",
          "The series exists only while the process answers scrapes, so a stopped bot does not match\n(InstanceDown covers that). A deploy reconnects in about 6 s.")
b += rule("WojtusEventHandlerFailures",
          f"sum({xi('wojtus_event_failures_total', '', '30m')}) > 20", "5m",
          '{{ $value | printf \\"%.0f\\" }} event handler failures in 30 minutes',
          "Normal is 0 to a few per day. Open the Events & Ingest dashboard, row 'Failures', for the event type and handler; then read failed_events in the database.")
b += rule("WojtusEventFailureRatioHigh",
          f"""sum({xi('wojtus_events_total', 'outcome="failed"', '30m')})
  / sum({xi('wojtus_events_total', '', '30m')}) > 0.05
and sum({xi('wojtus_events_total', '', '30m')}) >= 100""", "10m",
          "{{ $value | humanizePercentage }} of gateway events fail",
          "More than 5% of at least 100 events in 30 minutes had a failed handler. Check the bot log for 'Error handling' and whether Postgres accepts writes.",
          "Share of events with a failed handler. The 100-event floor keeps a quiet night out.")
b += rule("WojtusEventDeadLetter",
          f"sum by (event_type, handler)({xi('wojtus_event_dead_letters_total', '', '30m')}) > 0", None,
          "Dead letter for {{ $labels.event_type }} in {{ $labels.handler }}",
          "The database refused a failed-event row and the bot wrote it to the JSONL fallback file. The row needs a manual replay. Check Postgres and the fallback file on the bot volume.",
          "Any dead letter. The alert stays for 30 minutes after the last one.")
b += rule("WojtusDbUnwritable",
          f"max by (job, instance)(wojtus_db_unwritable_window_pending{{{J}}}) == 1", "5m",
          "The bot cannot write to Postgres",
          "An unwritable-database window is open for 5 minutes. Events of this time are lost. Check that wojtus-postgres is up and its disk is not full.")
b += rule("WojtusHeartbeatWriteFailures",
          f"sum({xi('wojtus_heartbeat_writes_total', NOT_OK, '10m')}) > 12", "2m",
          '{{ $value | printf \\"%.0f\\" }} heartbeat writes failed in 10 minutes',
          "The bot writes one heartbeat row every 5 s. More than 12 failures is over a minute without a write. Check Postgres connections and the bot log.")
b += rule("WojtusErrorLogBurst",
          f"sum({xi('wojtus_log_events_total', ERRORS, '15m')}) > 15", "5m",
          '{{ $value | printf \\"%.0f\\" }} error log events in 15 minutes',
          "Open the WojtusDiscord / Logs dashboard and read the error categories. A burst of this size is rare.",
          "Baseline from Loki, 7 days to 2026-10-06: 30 error lines, at most 11 in one 15-minute window.")
b += rule("WojtusHangfireFailedJobsGrowing",
          f"""max(wojtus_hangfire_jobs{{{J},state="failed"}})
  - max(wojtus_hangfire_jobs{{{J},state="failed"}} offset 1h) > 0""", "10m",
          '{{ $value | printf \\"%.0f\\" }} more failed Hangfire job(s) than one hour ago',
          "A background job failed after all its retries. Open /hangfire, tab Failed, and read the exception.",
          "The gauge reads the Hangfire tables, so a bot restart does not reset it.")
b += rule("WojtusBackfillRunFailed",
          f"sum by (type)({xi('wojtus_backfill_runs_total', FAILED, '1h')}) > 0", None,
          "Backfill {{ $labels.type }} failed",
          "A backfill run ended with an exception in the last hour. Search the bot log for 'backfill failed' and check the checkpoint row. A run a deploy cancels has outcome 'cancelled' and does not count.")
b += rule("WojtusRestartLoop",
          f"changes(wojtus_process_start_time_seconds{{{J}}}[1h]) >= 4", None,
          'The bot restarted {{ $value | printf \\"%.0f\\" }} times in one hour',
          "Check 'docker logs discord-event-service' for the exception before each exit, and docker_container_memory_oom_kills_total for an OOM kill.",
          "4 changes are 5 process starts within the hour. A deploy session of 4 starts in 49 minutes\n(2026-10-05 23:42 to 00:31) is 3 changes and does not fire.")
b += rule("WojtusConversationCostHigh",
          f"sum({xi('wojtus_conversation_cost_usd_total', '', '24h', '5m')}) > 2", "10m",
          'Conversation cost is {{ $value | printf \\"%.2f\\" }} USD in 24 hours',
          "Normal is a few cents a day. Open the Conversation & Memes dashboard for the model and the token counts, then the usage ledger for the user.",
          "The counter is what the provider billed for each call: the web search fee is inside it.")
b += rule("WojtusConversationUsageAlert",
          f"sum by (cap)({xi('wojtus_conversation_usage_alerts_total', '', '1h')}) > 0", None,
          "Conversation cost cap {{ $labels.cap }} was crossed",
          "The bot's own cost-cap alert fired in the last hour. Read the usage_alerts table and decide whether to keep the assistant on.")
b += rule("WojtusMemeSearchSlow",
          f"""histogram_quantile(0.95, sum by (le)({xi(MS + '_bucket', '', '1h')})) > 2.5
and sum({xi(MS + '_count', '', '1h')}) >= 20""", "10m",
          "Meme search p95 is {{ $value | humanizeDuration }}",
          "More than 5% of at least 20 searches in one hour took longer than 2.5 s. Normal is 1.5 to 1.9 s (issue #401), which reads as a p95 of 1.75 to 2 s. Open the Conversation & Memes dashboard, panel 'Mean search time by phase': a tall sql phase means Postgres (load, query plan, a larger table).",
          "p95 above 2.5 s, at least 20 searches in one hour. Buckets step 0.25 s from 0.5 to 2 s, then\n2.5 and 3 s (PR #420): searches of 1.5 to 1.9 s read as a p95 of at most 2 s, and 2.5 s is a\nbucket bound, so the rule says 'more than 5% took longer than 2.5 s'.\nWhy not the mean (the rule until 2026-10-07: mean > 3 s, 10 searches): 24 searches of 1.66 s\nand 6 of 4 s have a mean of 2.13 s and a p95 of 3.75 s. The mean is silent until every search\ntakes twice its time.\nWhy 20 searches: with 20 or more, one slow search is at most 5% and does not move the p95\n(19 of 1.7 s and 1 of 6 s read 1.75 s). With 10 the p95 is the slowest search.\nRestart-aware counts: searches are rare and the bot restarts on a deploy.")
b += rule("WojtusMemeSearchLogWriteFailed",
          f"sum({xi('wojtus_meme_search_log_writes_total', FAILED, '15m')}) > 0", None,
          '{{ $value | printf \\"%.0f\\" }} meme search log row(s) lost in 15 minutes',
          "The bot could not write a row of meme_search_log: that search is missing from the search log (the data of issue #384). The search itself answered. Search the bot log for the search log error and check that Postgres accepts writes.",
          "Any failed write. The alert stays for 15 minutes after the last one.")
b += rule("WojtusMemeDashboardUnavailable",
          f"""sum by (endpoint)({xi('wojtus_meme_dashboard_unavailable_total', 'reason=~"busy|refresh_timeout|refresh_failed"', '15m')}) > 20""", "5m",
          '{{ $value | printf \\"%.0f\\" }} meme dashboard requests to {{ $labels.endpoint }} answered 503 in 15 minutes',
          "The meme dashboard could not answer: the answer was still being computed after the wait limit (busy), or Discord gave no fresh thumbnail URL (refresh_timeout, refresh_failed). Open the Conversation & Memes dashboard, panel 'Dashboard requests unavailable (503)', for the reason; then Postgres load for busy, the bot log and Discord status for a refresh failure.",
          "Counted: busy, refresh_timeout, refresh_failed. Not counted: the caps doing their work\n(budget, wait_timeout, queue_full) and recent_failure (a failure of the last 30 s answered\nfrom memory: the failure itself is counted once).\nThreshold is a first guess: no baseline exists yet. Tune after a week of data.")
b += rule("WojtusApiServerErrors",
          f"""sum(increase({HSC}{{{J},{API},{ERR_5XX}}}[15m]))
  / sum(increase({HSC}{{{J},{API}}}[15m])) > 0.1
and sum(increase({HSC}{{{J},{API}}}[15m])) >= 20""", "5m",
          "{{ $value | humanizePercentage }} of dashboard API requests return 5xx",
          "More than 10% of at least 20 /api requests in 15 minutes failed with a 5xx other than 503. Check the bot log for unhandled exceptions and the Runtime & HTTP dashboard for the route.",
          "503 is left out: the meme dashboard answers it on purpose (WojtusMemeDashboardUnavailable).")
b += rule("WojtusBotMemoryHigh",
          'docker_container_memory_anon_bytes{name="discord-event-service"} > 1024 * 1024 * 1024', "30m",
          "The bot uses {{ $value | humanize1024 }}B of process memory",
          "Anonymous memory of the discord-event-service container is above 1 GiB for 30 minutes. Normal is about 160 MiB. Look for a leak: GC heap by generation on the Runtime & HTTP dashboard.",
          "Anonymous memory is process memory without the page cache. The container has no limit.")
b += rule("WojtusEventHandlerSlow",
          f"""histogram_quantile(0.95, sum by (le)(rate(wojtus_event_handler_duration_seconds_bucket{{{J}}}[15m]))) > 2
and sum(increase(wojtus_event_handler_duration_seconds_count{{{J}}}[15m])) >= 50""", "15m",
          "Event handler p95 is {{ $value | humanizeDuration }}",
          "The p95 of at least 50 events in 15 minutes is above 2 s. Normal is about 90 ms. Check Postgres (locks, long transactions) and the per-type panel on the Events & Ingest dashboard.",
          "Normal p95 is about 90 ms; the guild replay at a start (GuildCreated) takes 250 to 500 ms and is\na few events, well under 5% of 50. The buckets near the threshold end at 1, 2.5 and\n5 s (PR #420 kept them): the p95 reads above 2 s when more than 5% of the events take over\n2.5 s, or more than about 15% take over 1 s. rate() is enough: 50 events need series that exist.")
b += rule("WojtusHealthCheckWebhookFailed",
          f"sum({xi('wojtus_healthcheck_webhook_failures_total', '', '1h')}) > 0", None,
          "A bot health-check alert was not delivered",
          "HealthCheckJob could not send to its Discord webhook in the last hour, so one of its alerts reached nobody. Check the webhook URL and the bot log for the check name.")
b += rule("WojtusHealthEndpointDown",
          'max by (instance)(probe_success{job="wojtusdiscord-http"}) == 0', "3m",
          "The bot does not answer on its public URL",
          "The blackbox probe of {{ $labels.instance }} through Traefik fails for 3 minutes. If WojtusGatewayDisconnected is quiet the bot runs and the fault is in Traefik, DNS or the certificate; check probe_http_status_code and the Runtime & HTTP dashboard, row 'Public URL probe'.",
          "The probe runs every 30 s. A deploy takes the endpoint away for under a minute; 3 minutes is\nsix failed probes in a row.")
b += rule("WojtusHealthCheckFailing",
          f"max by (check)(wojtus_healthcheck_failing{{{J}}}) == 1", "10m",
          "Bot health check {{ $labels.check }} fails",
          "The bot's own HealthCheckJob reports {{ $labels.check }} as failing for 10 minutes (two runs). Open the Events & Ingest dashboard, row 'Health checks and downtime', for the value, and the bot log for the detail the job wrote.",
          "Mirrors the bot's own webhook alerts into Alertmanager: the webhook can fail, this cannot.\nThe job judges night silence itself (per-type thresholds), so the rule is quiet on an idle night.")
b += rule("WojtusHealthCheckStale",
          f"""time() - max by (job, instance)(wojtus_healthcheck_last_run_timestamp_seconds{{{J}}} > 0) > 900
or
max by (job, instance)(wojtus_process_uptime_seconds{{{J}}}) > 1200
  unless max by (job, instance)(wojtus_healthcheck_last_run_timestamp_seconds{{{J}}} > 0)""", "5m",
          "The bot's HealthCheckJob does not run",
          "The job runs every 5 minutes, and no run finished for 15 minutes (or none since a start 20 minutes ago). Its checks and the WojtusHealthCheckFailing alert are blind. Open /hangfire: is the recurring job there, is a run stuck in Processing?",
          "First branch: the last run is older than 15 minutes. Second branch: the process is up for\n20 minutes and the gauge is absent or 0, so no run finished since the start. A fresh start\nmatches neither.")
b += rule("WojtusTraceExportFailures",
          f"sum({xi('wojtus_trace_export_failures_total', '', '30m')}) > 5", "10m",
          '{{ $value | printf \\"%.0f\\" }} trace exports failed in 30 minutes',
          "The bot cannot send spans to Tempo, traces of this time are lost. Check that the tempo container runs and that Telemetry:OtlpTracesEndpoint points at it.",
          "A Tempo restart costs a few exports; more than 5 in 30 minutes for 10 minutes is an outage.")
b += rule("WojtusCommandErrors",
          f"""sum by (command)({xi('wojtus_command_executions_total', 'outcome="failed"', '1h')}) >= 3
and
sum by (command)({xi('wojtus_command_executions_total', 'outcome="failed"', '1h')})
  / sum by (command)({xi('wojtus_command_executions_total', '', '1h')}) > 0.3""", None,
          'Slash command {{ $labels.command }} fails',
          "At least 3 executions of /{{ $labels.command }} failed in one hour, more than 30% of its runs: an exception left the command, or the command caught its own error and told the user (/meme). Search the bot log for the command name.",
          "Only 'failed' counts: check_failed, bad_argument and cancelled are the user's side.")
b += rule("WojtusFkUnresolvedBurst",
          f"sum by (entity)({xi('wojtus_fk_unresolved_total', '', '15m')}) > 20", "5m",
          '{{ $value | printf \\"%.0f\\" }} unresolved {{ $labels.entity }} foreign keys in 15 minutes',
          "FkResolver could not find a required {{ $labels.entity }} row, so the events that need it were not written. A few after a start are normal (the entity sync is not done yet); a burst means the sync failed. Check the bot log and failed_events.",
          "Threshold is a first guess: no baseline exists yet. Tune after a week of data.")


def write(path=PATH):
    with open(path, "w") as f:
        f.write(HEAD + b.rstrip("\n") + "\n")
    return path

