name: Build and Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  packages: write

jobs:
  build-deploy:
    uses: wiktorkowalski/github-workflows/.github/workflows/dotnet-docker-deploy.yml@master
    with:
      image-name: ${{ github.repository }}/discord-event-service
      dotnet-project: src/DiscordEventService/DiscordEventService.csproj
      dockerfile: src/DiscordEventService/Dockerfile
      context: src/DiscordEventService
      deploy-compose-path: /home/ubuntu/docker/wojtusdiscord
      deploy-runner-labels: '["self-hosted", "homelab"]'
    secrets: inherit
